### ISSUE TITLE
It doesn't display in Edge.

### ISSUE THREAD

**Issue by ridesky** [heavyy/vue2-google-maps#1]
Hi friends. I appreciate that i can use vue2-google-maps. But may be there some trouble in Edge Browser, it does't display in Edge(I remember i could see the map in Edge before, maybe some issues in Microsoft?), have you seen this problems?
By the way, I'm from China, so these English may made you not very clearly.  : )

**Comment by tkjaergaard** [comment]
Hi @ridesky,

This is just a fork of https://github.com/xkjyeah/vue-google-maps

You should add your issue there instead :)
