### ISSUE TITLE
autobindAllEvents doesn't seems to work

### ISSUE THREAD

**Issue by ormedo** [heavyy/vue2-google-maps#6]
I Have this configuration
`
Vue.use(VueGoogleMaps, {
    load: {
      key: 'MY_KEY',
      libraries: 'places,drawing,visualization', 
    },
    autobindAllEvents: false,
});`

But componet emit all the events.
How i cant configure this property properly?

**Comment by tkjaergaard** [comment]
This is a fork of https://github.com/xkjyeah/vue-google-maps
